const hamburger = document.querySelector('.hamburger');
const navMenu = document.querySelector('.nav-menu');
const langSelect = document.querySelector('#lang-select');

const translations = {
    fr: {
        'nav.home': 'Accueil',
        'nav.profile': 'Profil',
        'nav.vision': 'Vision',
        'nav.formations': 'Formations',
        'nav.experience': 'Expérience',
        'nav.skills': 'Compétences',
        'nav.gallery': 'Galerie',
        'nav.contact': 'Contact',
        'hero.subtitle': 'Manager commercial & marketing | Chargé d’étude',
        'hero.lead': 'Profil pluridisciplinaire : sciences sociales, management, marketing et performance terrain.',
        'hero.cta.discover': 'Découvrir',
        'hero.cta.contact': 'Me contacter',
        'hero.badge.cdi': 'CDI à partir d’octobre 2026',
        'hero.badge.mobility': 'Mobilité appréciée',
        'hero.positioning.title': 'Positionnement',
        'hero.positioning.li1': 'Management commercial',
        'hero.positioning.li2': 'Marketing opérationnel',
        'hero.positioning.li3': 'Développement d’activité',
        'hero.highlight1.title': 'Double compétence',
        'hero.highlight1.text': 'Analyse + performance opérationnelle sur le terrain.',
        'hero.highlight2.title': 'Orientation résultats',
        'hero.highlight2.text': 'Pilotage par KPI, tableaux de bord et actions concrètes.',
        'hero.highlight3.title': 'Vision terrain',
        'hero.highlight3.text': 'Management, organisation, coordination et engagement client.',
        'about.title': 'Qui suis-je ?',
        'about.p1': 'Je suis Sinayoko Moro, diplômé d’un Master 2 Management Marketing et Commercial que j’ai réalisé en alternance. Mon parcours est volontairement pluridisciplinaire : il croise les sciences sociales, le management, le marketing et une expérience terrain solide dans la grande distribution.',
        'about.p2': 'Cette trajectoire m’a permis de développer une double compétence : comprendre les comportements humains, sociaux et consommateurs, et piloter la performance commerciale et opérationnelle sur le terrain.',
        'about.highlight': 'Je souhaite intégrer une entreprise en contrat à durée indéterminée dès octobre 2026, sur des fonctions orientées vers le management commercial, le marketing opérationnel ou le développement d’activité.',
        'about.profile': 'Profil pluridisciplinaire, capable d’assumer des responsabilités managériales, juridiques, de recherche et marketing stratégique & opérationnel.',
        'vision.title': 'Ma vision professionnelle',
        'vision.p1': 'Je conçois le management et le commerce comme un équilibre entre analyse, humain et performance. Mes études en anthropologie m’ont appris à observer, analyser et comprendre les logiques sociales, tandis que mes expériences en entreprise m’ont formé à l’action, la prise de décision et la responsabilité opérationnelle.',
        'vision.card1.title': 'Analyse',
        'vision.card1.text': 'Comprendre un environnement (marché, équipe, clients) pour décider avec recul.',
        'vision.card2.title': 'Stratégie',
        'vision.card2.text': 'Structurer une stratégie ou un plan d’action aligné sur les objectifs.',
        'vision.card3.title': 'Action',
        'vision.card3.text': 'Déployer concrètement sur le terrain, piloter et ajuster.',
        'edu.title': 'Formations & Apports',
        'edu.block1.title': 'Management, marketing et stratégie commerciale',
        'edu.block1.p1': 'Vision globale de l’entreprise orientée résultats.',
        'edu.block1.li1': 'Stratégie marketing et commerciale : analyse de marché, segmentation, ciblage, positionnement',
        'edu.block1.li2': 'Pilotage de la performance : suivi des indicateurs commerciaux, tableaux de bord, KPI',
        'edu.block1.li3': 'Gestion de projet : planification, coordination, respect des délais et des objectifs',
        'edu.block1.li4': 'Relation client et négociation : compréhension des besoins, adaptation de l’offre, fidélisation',
        'edu.block1.li5': 'Communication marketing : conception de messages, supports et actions de communication',
        'edu.block2.title': 'Sciences sociales & anthropologie',
        'edu.block2.li1': 'Capacité d’analyse approfondie des comportements individuels et collectifs',
        'edu.block2.li2': 'Compétences en enquête de terrain, observation et analyse qualitative',
        'edu.block2.li3': 'Forte capacité rédactionnelle et de synthèse',
        'edu.block2.li4': 'Esprit critique utile à la prise de recul stratégique',
        'edu.block2.p1': 'Atout majeur pour comprendre les comportements clients, les dynamiques d’équipe et les enjeux culturels et sociaux en entreprise.',
        'edu.timeline1.title': 'Master 2 Management, Marketing et Commercial',
        'edu.timeline1.meta': 'École de commerce Paris Com\'Sup — Diplômé',
        'edu.timeline1.p': 'Stratégie marketing et commerciale : analyses de marché, segmentation pertinente, identification des cibles et définition du positionnement. Pilotage de la performance : gestion des indicateurs commerciaux via tableaux de bord et KPIs. Expérience en gestion de projet, relation client, négociation et communication marketing. Vision globale orientée résultats.',
        'edu.timeline2.title': 'Master 2 Sciences Sociales - Parcours Anthropologie',
        'edu.timeline2.meta': 'Université Paris Nanterre & Paris 8 — Diplômé',
        'edu.timeline2.p': 'Socle analytique majeur : analyse des comportements individuels et collectifs, enquête de terrain, observation et analyse qualitative.',
        'edu.timeline3.title': 'Licence Sciences Humaines et Sociales - Parcours Anthropologie',
        'edu.timeline3.meta': 'Université Paris Nanterre — Diplômé',
        'edu.timeline3.p': 'Formation en sciences humaines et sociales avec spécialisation en anthropologie.',
        'edu.timeline4.title': 'Licence Administration Économique et Sociale (AES)',
        'edu.timeline4.meta': 'Université Paris 8 — Diplômé',
        'edu.timeline4.p': 'Formation pluridisciplinaire combinant économie, droit, gestion et sciences sociales.',
        'exp.title': 'Expérience professionnelle',
        'exp.card1.title': 'Management et distribution',
        'exp.card1.p': 'Adjoint Responsable de Magasin : posture managériale et pilotage opérationnel.',
        'exp.card1.li1': 'Encadrement et coordination des équipes',
        'exp.card1.li2': 'Gestion administrative (RH, caisse, casse, procédures)',
        'exp.card1.li3': 'Pilotage des stocks et des flux',
        'exp.card1.li4': 'Gestion des commandes fournisseurs et livraisons',
        'exp.card1.li5': 'Optimisation de l’organisation et de la performance',
        'exp.card2.title': 'Relation client et performance commerciale',
        'exp.card2.p': 'Carrefour Market : maîtrise de la relation client et gestion de rayon.',
        'exp.card2.li1': 'Sens du service et du conseil client',
        'exp.card2.li2': 'Mise en valeur des produits',
        'exp.card2.li3': 'Participation aux commandes et stocks',
        'exp.card2.li4': 'Compréhension de l’impact sur le chiffre d’affaires',
        'exp.card3.title': 'Gestion de projet & évènementiel',
        'exp.card3.p': 'Structuration et pilotage de projet : cahier des charges, coordination logistique et suivi.',
        'exp.card4.title': 'Communication & engagement associatif',
        'exp.card4.li1': 'Définition d’une stratégie de communication',
        'exp.card4.li2': 'Création de supports et contenus',
        'exp.card4.li3': 'Promotion de projets culturels',
        'exp.card4.li4': 'Valorisation d’une application digitale',
        'skills.title': 'Compétences clés',
        'skills.chip1': 'Management d’équipe & organisation',
        'skills.chip2': 'Stratégie commerciale et marketing',
        'skills.chip3': 'Analyse de données & études',
        'skills.chip4': 'Gestion de projet',
        'skills.chip5': 'Communication & outils digitaux',
        'skills.tools.title': 'Outils',
        'skills.tools.p': 'Pack Office, Canva, analyse de données, WordPress (débutant), Suite Adobe (débutant)',
        'skills.lang.title': 'Langues',
        'skills.lang.li1': 'Français : langue maternelle',
        'skills.lang.li2': 'Anglais : B2',
        'skills.lang.li3': 'Allemand : A2',
        'gallery.title': 'Galerie',
        'contact.title': 'Informations complémentaires',
        'contact.card1.title': 'Coordonnées',
        'contact.card1.cta': 'Contacter sur WhatsApp',
        'contact.card2.title': 'Disponibilité',
        'contact.card2.p1': 'CDI à partir d’octobre 2026',
        'contact.card2.p2': '🚗 Permis B',
        'contact.card2.p3': 'Mobilité appréciée selon le poste',
        'contact.card3.title': 'LinkedIn',
        'footer.text': '© 2026 Sinayoko Moro — Portfolio professionnel'
    },
    en: {
        'nav.home': 'Home',
        'nav.profile': 'Profile',
        'nav.vision': 'Vision',
        'nav.formations': 'Education',
        'nav.experience': 'Experience',
        'nav.skills': 'Skills',
        'nav.gallery': 'Gallery',
        'nav.contact': 'Contact',
        'hero.subtitle': 'Commercial & marketing manager | Research officer',
        'hero.lead': 'Multidisciplinary profile: social sciences, management, marketing and field performance.',
        'hero.cta.discover': 'Discover',
        'hero.cta.contact': 'Contact me',
        'hero.badge.cdi': 'Full-time from October 2026',
        'hero.badge.mobility': 'Mobility considered',
        'hero.positioning.title': 'Positioning',
        'hero.positioning.li1': 'Commercial management',
        'hero.positioning.li2': 'Operational marketing',
        'hero.positioning.li3': 'Business development',
        'hero.highlight1.title': 'Dual expertise',
        'hero.highlight1.text': 'Analysis + operational performance in the field.',
        'hero.highlight2.title': 'Results-driven',
        'hero.highlight2.text': 'KPI-driven management, dashboards and concrete actions.',
        'hero.highlight3.title': 'Field insight',
        'hero.highlight3.text': 'Management, organization, coordination and client engagement.',
        'about.title': 'Who am I?',
        'about.p1': 'I am Sinayoko Moro, a graduate with a Master’s degree in Management, Marketing and Commercial Strategy completed through a work-study program. My path is deliberately multidisciplinary, combining social sciences, management, marketing and solid field experience in retail.',
        'about.p2': 'This journey gave me a dual competence: understanding human, social and consumer behaviors, and driving commercial and operational performance on the ground.',
        'about.highlight': 'I aim to join a company on a permanent contract from October 2026, in roles focused on commercial management, operational marketing or business development.',
        'about.profile': 'A multidisciplinary profile able to take on managerial, legal, research, and strategic & operational marketing responsibilities.',
        'vision.title': 'My professional vision',
        'vision.p1': 'I see management and commerce as a balance between analysis, people and performance. My anthropology studies taught me to observe, analyze and understand social dynamics, while my corporate experience trained me in action, decision-making and operational responsibility.',
        'vision.card1.title': 'Analysis',
        'vision.card1.text': 'Understand an environment (market, team, clients) to decide with perspective.',
        'vision.card2.title': 'Strategy',
        'vision.card2.text': 'Structure a strategy or action plan aligned with objectives.',
        'vision.card3.title': 'Action',
        'vision.card3.text': 'Deploy concretely in the field, manage and adjust.',
        'edu.title': 'Education & Value',
        'edu.block1.title': 'Management, marketing and commercial strategy',
        'edu.block1.p1': 'A global, results-oriented view of the company.',
        'edu.block1.li1': 'Marketing and commercial strategy: market analysis, segmentation, targeting, positioning',
        'edu.block1.li2': 'Performance management: tracking commercial indicators, dashboards, KPIs',
        'edu.block1.li3': 'Project management: planning, coordination, deadlines and objectives',
        'edu.block1.li4': 'Client relations and negotiation: needs analysis, offer adaptation, loyalty',
        'edu.block1.li5': 'Marketing communication: design of messages, materials and actions',
        'edu.block2.title': 'Social sciences & anthropology',
        'edu.block2.li1': 'Deep analysis of individual and collective behaviors',
        'edu.block2.li2': 'Field research skills, observation and qualitative analysis',
        'edu.block2.li3': 'Strong writing and synthesis capabilities',
        'edu.block2.li4': 'Critical thinking for strategic perspective',
        'edu.block2.p1': 'A major asset to understand customer behaviors, team dynamics and cultural/social challenges in business.',
        'edu.timeline1.title': 'Master 2 in Management, Marketing and Commercial Strategy',
        'edu.timeline1.meta': 'Paris Com\'Sup Business School — Graduated',
        'edu.timeline1.p': 'Marketing and commercial strategy: market analysis, segmentation, target identification and positioning. Performance management via dashboards and KPIs. Experience in project management, client relations, negotiation and marketing communication. Results-oriented global vision.',
        'edu.timeline2.title': 'Master 2 in Social Sciences - Anthropology Track',
        'edu.timeline2.meta': 'Université Paris Nanterre & Paris 8 — Graduated',
        'edu.timeline2.p': 'Strong analytical foundation: analysis of individual and collective behaviors, field research, observation and qualitative analysis.',
        'edu.timeline3.title': 'Bachelor in Social Sciences - Anthropology Track',
        'edu.timeline3.meta': 'Université Paris Nanterre — Graduated',
        'edu.timeline3.p': 'Training in social sciences with a specialization in anthropology.',
        'edu.timeline4.title': 'Bachelor in Economics and Social Administration (AES)',
        'edu.timeline4.meta': 'Université Paris 8 — Graduated',
        'edu.timeline4.p': 'Multidisciplinary training combining economics, law, management and social sciences.',
        'exp.title': 'Professional experience',
        'exp.card1.title': 'Management and retail',
        'exp.card1.p': 'Assistant store manager: managerial posture and operational leadership.',
        'exp.card1.li1': 'Team management and coordination',
        'exp.card1.li2': 'Administrative management (HR, cash, losses, procedures)',
        'exp.card1.li3': 'Stock and flow management',
        'exp.card1.li4': 'Supplier orders and deliveries management',
        'exp.card1.li5': 'Organization and performance optimization',
        'exp.card2.title': 'Customer relations & commercial performance',
        'exp.card2.p': 'Carrefour Market: strong client relations and department management.',
        'exp.card2.li1': 'Service mindset and customer advice',
        'exp.card2.li2': 'Product presentation and merchandising',
        'exp.card2.li3': 'Participation in orders and stock management',
        'exp.card2.li4': 'Understanding of commercial impact on revenue',
        'exp.card3.title': 'Project & event management',
        'exp.card3.p': 'Project structuring and delivery: specifications, logistics coordination and follow-up.',
        'exp.card4.title': 'Communication & community engagement',
        'exp.card4.li1': 'Definition of a communication strategy',
        'exp.card4.li2': 'Creation of materials and content',
        'exp.card4.li3': 'Promotion of cultural projects',
        'exp.card4.li4': 'Promotion of a digital application',
        'skills.title': 'Key skills',
        'skills.chip1': 'Team management & organization',
        'skills.chip2': 'Commercial strategy and marketing',
        'skills.chip3': 'Data analysis & research',
        'skills.chip4': 'Project management',
        'skills.chip5': 'Communication & digital tools',
        'skills.tools.title': 'Tools',
        'skills.tools.p': 'Office suite, Canva, data analysis, WordPress (beginner), Adobe suite (beginner)',
        'skills.lang.title': 'Languages',
        'skills.lang.li1': 'French: native',
        'skills.lang.li2': 'English: B2',
        'skills.lang.li3': 'German: A2',
        'gallery.title': 'Gallery',
        'contact.title': 'Additional information',
        'contact.card1.title': 'Contact details',
        'contact.card1.cta': 'Contact on WhatsApp',
        'contact.card2.title': 'Availability',
        'contact.card2.p1': 'Full-time from October 2026',
        'contact.card2.p2': '🚗 Driver’s license',
        'contact.card2.p3': 'Mobility depending on role',
        'contact.card3.title': 'LinkedIn',
        'footer.text': '© 2026 Sinayoko Moro — Professional portfolio'
    }
};

const applyLanguage = (lang) => {
    const dict = translations[lang] || translations.fr;
    document.documentElement.lang = lang;
    document.querySelectorAll('[data-i18n]').forEach((el) => {
        const key = el.getAttribute('data-i18n');
        if (dict[key]) {
            el.textContent = dict[key];
        }
    });
};

if (langSelect) {
    langSelect.addEventListener('change', (event) => {
        applyLanguage(event.target.value);
    });
    applyLanguage(langSelect.value || 'fr');
}

if (hamburger && navMenu) {
    hamburger.addEventListener('click', () => {
        navMenu.classList.toggle('active');
    });

    document.querySelectorAll('.nav-menu a').forEach((link) => {
        link.addEventListener('click', () => {
            navMenu.classList.remove('active');
        });
    });
}
