const hamburger = document.querySelector('.hamburger');
const navMenu = document.querySelector('.nav-menu');
const langSelect = document.querySelector('#lang-select');

const translations = {
    fr: {
        'nav.home': 'Accueil',
        'nav.profile': 'Profil',
        'nav.vision': 'Vision',
        'nav.formations': 'Formations',
        'nav.experience': 'Expérience',
        'nav.ia': 'Outils IA',
        'nav.skills': 'Compétences',
        'nav.gallery': 'Galerie',
        'nav.contact': 'Contact',
        'hero.subtitle': 'Manager commercial & marketing | Chargé d’étude',
        'hero.lead': 'Manager terrain et analyste de formation : je pilote la performance commerciale au quotidien et je la comprends en profondeur.',
        'hero.cta.discover': 'Découvrir',
        'hero.cta.contact': 'Me contacter',
        'hero.badge.cdi': 'CDI dès octobre 2026',
        'hero.badge.mobility': 'Mobilité appréciée',
        'hero.positioning.title': 'Positionnement',
        'hero.positioning.li1': 'Management commercial',
        'hero.positioning.li2': 'Marketing opérationnel',
        'hero.positioning.li3': 'Développement d’activité',
        'hero.highlight1.title': 'Double compétence',
        'hero.highlight1.text': 'Lire les comportements humains et consommateurs, et transformer cette lecture en résultats commerciaux et opérationnels.',
        'hero.highlight2.title': 'Orientation résultats',
        'hero.highlight2.text': 'Pilotage par KPI, tableaux de bord et actions concrètes.',
        'hero.highlight3.title': 'Vision terrain',
        'hero.highlight3.text': 'Management, organisation, coordination et engagement client.',
        'about.title': 'Qui suis-je ?',
        'about.p1': 'Manager terrain et analyste de formation : je pilote la performance commerciale au quotidien et je la comprends en profondeur. Double Master en poche (Management Commercial Marketing et Anthropologie), je croise l’action et l’observation pour décider vite et juste.',
        'about.p2': 'Ma double compétence : lire les comportements humains et consommateurs, et transformer cette lecture en résultats commerciaux et opérationnels sur le terrain.',
        'about.highlight': 'Objectif : un CDI dès octobre 2026, sur des fonctions de management commercial, marketing opérationnel ou développement d’activité. Mon profil pluridisciplinaire me permet d’être opérationnel aussi bien sur des missions managériales que sur des sujets d’étude, de recherche ou de marketing stratégique.',
        'about.profile': 'Profil pluridisciplinaire, opérationnel aussi bien sur des missions managériales que sur des sujets d’étude, de recherche ou de marketing stratégique.',
        'vision.title': 'Ma vision professionnelle',
        'vision.p1': 'Le management et le commerce sont un équilibre entre analyse, humain et performance. L’anthropologie m’a appris à observer et décoder les logiques sociales ; le terrain m’a formé à décider et à agir vite.',
        'vision.card1.title': 'Analyse',
        'vision.card1.text': 'Analyser un environnement — marché, équipe, clients — pour décider avec recul.',
        'vision.card2.title': 'Stratégie',
        'vision.card2.text': 'Structurer une stratégie ou un plan d’action clair.',
        'vision.card3.title': 'Action',
        'vision.card3.text': 'Le déployer concrètement et l’ajuster sur le terrain.',
        'edu.title': 'Ce que mes formations m’ont apporté',
        'edu.block1.title': 'Management, marketing et stratégie commerciale',
        'edu.block1.lead': 'Une vision globale de l’entreprise, orientée résultats :',
        'edu.block1.li1': 'Stratégie marketing et commerciale : analyse de marché, segmentation, ciblage, positionnement',
        'edu.block1.li2': 'Pilotage de la performance : indicateurs commerciaux, tableaux de bord, KPI',
        'edu.block1.li3': 'Gestion de projet : planification, coordination, tenue des délais et des objectifs',
        'edu.block1.li4': 'Relation client et négociation : compréhension des besoins, adaptation de l’offre, fidélisation',
        'edu.block1.li5': 'Communication marketing : messages, supports et actions de communication',
        'edu.block1.p2': 'Résultat : relier vision stratégique et efficacité opérationnelle.',
        'edu.block2.title': 'Sciences sociales & anthropologie : comprendre pour mieux agir',
        'edu.block2.lead': 'Le socle analytique de mon profil :',
        'edu.block2.li1': 'Analyse fine des comportements individuels et collectifs',
        'edu.block2.li2': 'Enquête de terrain, observation, analyse qualitative',
        'edu.block2.li3': 'Capacité rédactionnelle et de synthèse',
        'edu.block2.li4': 'Esprit critique au service de la prise de recul stratégique',
        'edu.block2.p1': 'Un atout direct pour décoder les comportements clients, les dynamiques d’équipe et les enjeux culturels en entreprise.',
        'edu.timeline1.title': 'Master 2 Management, Marketing et Commercial',
        'edu.timeline1.meta': 'École de commerce Paris Com\'Sup — Diplômé',
        'edu.timeline1.p': 'Analyses de marché, segmentation, ciblage, positionnement. Pilotage de la performance via tableaux de bord et KPI. Gestion de projet, relation client, négociation, communication marketing. Vision globale de l’entreprise, orientée résultats.',
        'edu.timeline2.title': 'Master 2 Sciences Sociales - Parcours Anthropologie',
        'edu.timeline2.meta': 'Université Paris Nanterre & Paris 8 — Diplômé',
        'edu.timeline2.p': 'Socle analytique majeur : analyse des comportements individuels et collectifs, enquête de terrain, observation et analyse qualitative.',
        'edu.timeline3.title': 'Licence Sociologie et Anthropologie',
        'edu.timeline3.meta': 'Université Paris Nanterre — Diplômé',
        'edu.timeline3.p': 'Formation en sciences humaines et sociales avec spécialisation en anthropologie.',
        'edu.timeline3.note': 'Formation complémentaire : Licence Administration, Économie et Social (AES) — Université Paris 8, suivie en parallèle. Socle pluridisciplinaire en économie, droit, gestion et sciences sociales.',
        'exp.title': 'Mon expérience professionnelle en pratique',
        'exp.card1.title': 'Management et distribution',
        'exp.card1.meta': 'Responsable Adjoint de Magasin — Action, Bobigny (alternance) — Août 2024 – Sept. 2026',
        'exp.card1.lead': 'Posture managériale complète sur un point de vente :',
        'exp.card1.li1': 'Encadrement et coordination d’équipe au quotidien',
        'exp.card1.li2': 'Gestion administrative : RH, caisse, casse, procédures',
        'exp.card1.li3': 'Pilotage des stocks et des flux',
        'exp.card1.li4': 'Commandes fournisseurs et livraisons',
        'exp.card1.li5': 'Optimisation de l’organisation et de la performance du magasin',
        'exp.card1.result': 'Résultat : décisions rapides sous pression opérationnelle, exigence terrain maintenue en continu.',
        'exp.card2.title': 'Relation client et performance commerciale',
        'exp.card2.meta': 'Employé Commercial de Rayon — Carrefour Market PSG — Fév. – Avr. 2024',
        'exp.card2.lead': 'Maîtrise concrète de la relation client et de la gestion de rayon :',
        'exp.card2.li1': 'Sens du service et du conseil client',
        'exp.card2.li2': 'Gestion des assortiments et mise en valeur des produits',
        'exp.card2.li3': 'Participation active aux commandes et à la gestion des stocks',
        'exp.card2.li4': 'Impact direct des décisions commerciales sur le chiffre d’affaires',
        'exp.card3.title': 'Gestion de projet & évènementiel',
        'exp.card3.meta': 'Chef de Projet Événementiel — Université Paris 8 — Sept. 2022 – Mai 2023',
        'exp.card3.lead': 'Un projet piloté de bout en bout :',
        'exp.card3.li1': 'Rédaction du cahier des charges',
        'exp.card3.li2': 'Coordination logistique',
        'exp.card3.li3': 'Pilotage des parties prenantes',
        'exp.card3.li4': 'Animation et suivi de l’événement',
        'exp.card3.result': 'Résultat : gestion du temps, communication et travail d’équipe renforcés.',
        'exp.card4.title': 'Commercial B2B — Packagings Alimentaires',
        'exp.card4.meta': 'Penta-Plast, Paris — Juin – Oct. 2020',
        'exp.card4.lead': 'Une première expérience commerciale B2B et logistique terrain :',
        'exp.card4.li1': 'Promotion et présentation d’échantillons pour des collaborations clients',
        'exp.card4.li2': 'Suivi et coordination de la logistique d’expédition',
        'exp.card4.li3': 'Gestion des stocks et optimisation de l’emplacement des marchandises',
        'exp.card4.li4': 'Création de supports et rédaction de contenus',
        'exp.card5.title': 'Communication & engagement associatif',
        'exp.card5.meta': 'Chargé de Communication (bénévolat) — Association RVP — Un repas et un vêtement pour eux',
        'exp.card5.lead': 'Une approche créative et stratégique de la communication :',
        'exp.card5.li1': 'Définition d’une stratégie de communication',
        'exp.card5.li2': 'Création de supports et contenus',
        'exp.card5.li3': 'Promotion de projets et d’événements culturels',
        'exp.card5.li4': 'Valorisation d’une application digitale',
        'ia.title': 'Maîtrise des outils de l’IA',
        'ia.lead': 'Des outils IA intégrés à mes missions quotidiennes — rapports, veille, création de supports, argumentaires :',
        'ia.chip1': 'Claude — rapports & synthèses',
        'ia.chip2': 'Canva IA — visuels professionnels',
        'ia.chip3': 'Google Flow — automatisation',
        'ia.chip4': 'Gemini — veille & étude de marché',
        'ia.chip5': 'ChatGPT — argumentaires',
        'ia.chip6': 'Perplexity — recherche fiable',
        'ia.chip7': 'Kimi — synthèses rapides',
        'ia.chip8': 'NotebookLM — notes de synthèse',
        'ia.chip9': 'Gamma — présentations',
        'skills.title': 'Compétences clés',
        'skills.chip1': 'Management d’équipe & organisation',
        'skills.chip2': 'Stratégie commerciale et marketing',
        'skills.chip3': 'Analyse de données & études',
        'skills.chip4': 'Gestion de projet',
        'skills.chip5': 'Communication et outils digitaux',
        'skills.tools.title': 'Outils',
        'skills.tools.p': 'Pack Office, Canva, analyse de données',
        'skills.lang.title': 'Langues',
        'skills.lang.li1': 'Français : langue maternelle',
        'skills.lang.li2': 'Anglais : B2',
        'skills.lang.li3': 'Allemand : A2',
        'gallery.title': 'Galerie',
        'contact.now.title': 'Et maintenant ?',
        'contact.now.lead': 'Je cherche une entreprise où :',
        'contact.now.li1': 'Développer mes compétences managériales et commerciales',
        'contact.now.li2': 'Contribuer concrètement à la performance',
        'contact.now.li3': 'Évoluer sur le long terme',
        'contact.now.avail': 'Disponible pour un CDI à partir d’octobre 2026.',
        'contact.title': 'Informations complémentaires',
        'contact.card1.title': 'Coordonnées',
        'contact.card1.cta': 'Contacter sur WhatsApp',
        'contact.card2.title': 'Disponibilité',
        'contact.card2.p1': 'CDI à partir d’octobre 2026',
        'contact.card2.p2': '🚗 Permis B',
        'contact.card2.p3': 'Mobilité appréciée selon le poste',
        'contact.card3.title': 'LinkedIn',
        'footer.text': '© 2026 Sinayoko Moro — Portfolio professionnel'
    },
    en: {
        'nav.home': 'Home',
        'nav.profile': 'Profile',
        'nav.vision': 'Vision',
        'nav.formations': 'Education',
        'nav.experience': 'Experience',
        'nav.ia': 'AI Tools',
        'nav.skills': 'Skills',
        'nav.gallery': 'Gallery',
        'nav.contact': 'Contact',
        'hero.subtitle': 'Commercial & marketing manager | Research officer',
        'hero.lead': 'Field manager and trained analyst: I drive commercial performance day to day and understand it in depth.',
        'hero.cta.discover': 'Discover',
        'hero.cta.contact': 'Contact me',
        'hero.badge.cdi': 'Full-time from October 2026',
        'hero.badge.mobility': 'Mobility considered',
        'hero.positioning.title': 'Positioning',
        'hero.positioning.li1': 'Commercial management',
        'hero.positioning.li2': 'Operational marketing',
        'hero.positioning.li3': 'Business development',
        'hero.highlight1.title': 'Dual expertise',
        'hero.highlight1.text': 'Reading human and consumer behavior, and turning it into commercial and operational results.',
        'hero.highlight2.title': 'Results-driven',
        'hero.highlight2.text': 'KPI-driven management, dashboards and concrete actions.',
        'hero.highlight3.title': 'Field insight',
        'hero.highlight3.text': 'Management, organization, coordination and client engagement.',
        'about.title': 'Who am I?',
        'about.p1': 'Field manager and trained analyst: I drive commercial performance day to day and understand it in depth. With a double Master’s degree (Commercial & Marketing Management and Anthropology), I combine action and observation to decide fast and right.',
        'about.p2': 'My dual competence: reading human and consumer behavior, and turning that insight into commercial and operational results on the ground.',
        'about.highlight': 'Goal: a permanent contract from October 2026, in commercial management, operational marketing or business development roles. My multidisciplinary profile lets me be effective on managerial missions as well as on research, study or strategic marketing topics.',
        'about.profile': 'A multidisciplinary profile, effective on managerial missions as well as on research, study or strategic marketing topics.',
        'vision.title': 'My professional vision',
        'vision.p1': 'Management and business are a balance between analysis, people and performance. Anthropology taught me to observe and decode social dynamics; the field trained me to decide and act fast.',
        'vision.card1.title': 'Analysis',
        'vision.card1.text': 'Analyze an environment — market, team, clients — to decide with perspective.',
        'vision.card2.title': 'Strategy',
        'vision.card2.text': 'Structure a clear strategy or action plan.',
        'vision.card3.title': 'Action',
        'vision.card3.text': 'Deploy it concretely and adjust it in the field.',
        'edu.title': 'What my education has given me',
        'edu.block1.title': 'Management, marketing and commercial strategy',
        'edu.block1.lead': 'A global, results-oriented view of the company:',
        'edu.block1.li1': 'Marketing and commercial strategy: market analysis, segmentation, targeting, positioning',
        'edu.block1.li2': 'Performance management: commercial indicators, dashboards, KPIs',
        'edu.block1.li3': 'Project management: planning, coordination, meeting deadlines and objectives',
        'edu.block1.li4': 'Client relations and negotiation: understanding needs, adapting the offer, loyalty',
        'edu.block1.li5': 'Marketing communication: messages, materials and communication actions',
        'edu.block1.p2': 'Result: connecting strategic vision with operational efficiency.',
        'edu.block2.title': 'Social sciences & anthropology: understanding to act better',
        'edu.block2.lead': 'The analytical foundation of my profile:',
        'edu.block2.li1': 'Deep analysis of individual and collective behaviors',
        'edu.block2.li2': 'Field research, observation, qualitative analysis',
        'edu.block2.li3': 'Strong writing and synthesis skills',
        'edu.block2.li4': 'Critical thinking in service of strategic perspective',
        'edu.block2.p1': 'A direct asset for decoding customer behavior, team dynamics and cultural issues in business.',
        'edu.timeline1.title': 'Master 2 in Management, Marketing and Commercial Strategy',
        'edu.timeline1.meta': 'Paris Com\'Sup Business School — Graduated',
        'edu.timeline1.p': 'Market analysis, segmentation, targeting, positioning. Performance management via dashboards and KPIs. Project management, client relations, negotiation, marketing communication. Results-oriented global vision of the company.',
        'edu.timeline2.title': 'Master 2 in Social Sciences - Anthropology Track',
        'edu.timeline2.meta': 'Université Paris Nanterre & Paris 8 — Graduated',
        'edu.timeline2.p': 'Major analytical foundation: analysis of individual and collective behaviors, field research, observation and qualitative analysis.',
        'edu.timeline3.title': 'Bachelor in Sociology and Anthropology',
        'edu.timeline3.meta': 'Université Paris Nanterre — Graduated',
        'edu.timeline3.p': 'Training in social sciences and humanities with a specialization in anthropology.',
        'edu.timeline3.note': 'Complementary training: Bachelor in Economics and Social Administration (AES) — Université Paris 8, taken in parallel. Multidisciplinary foundation in economics, law, management and social sciences.',
        'exp.title': 'My professional experience in practice',
        'exp.card1.title': 'Management and retail',
        'exp.card1.meta': 'Assistant Store Manager — Action, Bobigny (work-study) — Aug. 2024 – Sept. 2026',
        'exp.card1.lead': 'Full managerial posture across a retail location:',
        'exp.card1.li1': 'Day-to-day team supervision and coordination',
        'exp.card1.li2': 'Administrative management: HR, cash, losses, procedures',
        'exp.card1.li3': 'Stock and flow management',
        'exp.card1.li4': 'Supplier orders and deliveries',
        'exp.card1.li5': 'Optimizing store organization and performance',
        'exp.card1.result': 'Result: fast decisions under operational pressure, field standards maintained continuously.',
        'exp.card2.title': 'Customer relations & commercial performance',
        'exp.card2.meta': 'Retail Sales Associate — Carrefour Market PSG — Feb. – Apr. 2024',
        'exp.card2.lead': 'Hands-on mastery of customer relations and department management:',
        'exp.card2.li1': 'Service mindset and customer advice',
        'exp.card2.li2': 'Assortment management and product merchandising',
        'exp.card2.li3': 'Active participation in orders and stock management',
        'exp.card2.li4': 'Direct impact of commercial decisions on revenue',
        'exp.card3.title': 'Project & event management',
        'exp.card3.meta': 'Event Project Manager — Université Paris 8 — Sept. 2022 – May 2023',
        'exp.card3.lead': 'A project managed end to end:',
        'exp.card3.li1': 'Drafting the project specifications',
        'exp.card3.li2': 'Logistics coordination',
        'exp.card3.li3': 'Stakeholder management',
        'exp.card3.li4': 'Running and follow-up of the event',
        'exp.card3.result': 'Result: stronger time management, communication and teamwork.',
        'exp.card4.title': 'B2B Sales — Food Packaging',
        'exp.card4.meta': 'Penta-Plast, Paris — June – Oct. 2020',
        'exp.card4.lead': 'A first B2B sales and field logistics experience:',
        'exp.card4.li1': 'Promoting and presenting samples for client partnerships',
        'exp.card4.li2': 'Tracking and coordinating shipping logistics',
        'exp.card4.li3': 'Stock management and optimizing goods placement',
        'exp.card4.li4': 'Creating materials and writing content',
        'exp.card5.title': 'Communication & community engagement',
        'exp.card5.meta': 'Communications Officer (volunteer) — RVP Association — A meal and clothing for those in need',
        'exp.card5.lead': 'A creative and strategic approach to communication:',
        'exp.card5.li1': 'Defining a communication strategy',
        'exp.card5.li2': 'Creating materials and content',
        'exp.card5.li3': 'Promoting cultural projects and events',
        'exp.card5.li4': 'Showcasing a digital application',
        'ia.title': 'AI tools mastery',
        'ia.lead': 'AI tools built into my daily work — reports, monitoring, content creation, sales pitches:',
        'ia.chip1': 'Claude — reports & summaries',
        'ia.chip2': 'Canva AI — professional visuals',
        'ia.chip3': 'Google Flow — automation',
        'ia.chip4': 'Gemini — monitoring & market research',
        'ia.chip5': 'ChatGPT — sales pitches',
        'ia.chip6': 'Perplexity — reliable research',
        'ia.chip7': 'Kimi — quick summaries',
        'ia.chip8': 'NotebookLM — synthesis notes',
        'ia.chip9': 'Gamma — presentations',
        'skills.title': 'Key skills',
        'skills.chip1': 'Team management & organization',
        'skills.chip2': 'Commercial strategy and marketing',
        'skills.chip3': 'Data analysis & research',
        'skills.chip4': 'Project management',
        'skills.chip5': 'Communication and digital tools',
        'skills.tools.title': 'Tools',
        'skills.tools.p': 'Office suite, Canva, data analysis',
        'skills.lang.title': 'Languages',
        'skills.lang.li1': 'French: native',
        'skills.lang.li2': 'English: B2',
        'skills.lang.li3': 'German: A2',
        'gallery.title': 'Gallery',
        'contact.now.title': 'What’s next?',
        'contact.now.lead': 'I am looking for a company where I can:',
        'contact.now.li1': 'Develop my managerial and commercial skills',
        'contact.now.li2': 'Contribute concretely to performance',
        'contact.now.li3': 'Grow over the long term',
        'contact.now.avail': 'Available for a full-time role from October 2026.',
        'contact.title': 'Additional information',
        'contact.card1.title': 'Contact details',
        'contact.card1.cta': 'Contact on WhatsApp',
        'contact.card2.title': 'Availability',
        'contact.card2.p1': 'Full-time from October 2026',
        'contact.card2.p2': '🚗 Driver’s license',
        'contact.card2.p3': 'Mobility depending on role',
        'contact.card3.title': 'LinkedIn',
        'footer.text': '© 2026 Sinayoko Moro — Professional portfolio'
    }
};

const applyLanguage = (lang) => {
    const dict = translations[lang] || translations.fr;
    document.documentElement.lang = lang;
    document.querySelectorAll('[data-i18n]').forEach((el) => {
        const key = el.getAttribute('data-i18n');
        if (dict[key]) {
            el.textContent = dict[key];
        }
    });
};

if (langSelect) {
    langSelect.addEventListener('change', (event) => {
        applyLanguage(event.target.value);
    });
    applyLanguage(langSelect.value || 'fr');
}

if (hamburger && navMenu) {
    hamburger.addEventListener('click', () => {
        navMenu.classList.toggle('active');
    });

    document.querySelectorAll('.nav-menu a').forEach((link) => {
        link.addEventListener('click', () => {
            navMenu.classList.remove('active');
        });
    });
}
